# Generated by Django 5.2.8 on 2025-12-02 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='uploaded_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='resume',
            old_name='job_seeker',
            new_name='jobseeker',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='description',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='related_job',
        ),
        migrations.AddField(
            model_name='resume',
            name='education',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
