# Generated by Django 5.2.10 on 2026-02-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_user_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="sms_activation_code",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="sms_activation_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
