# Generated by Django 5.2.10 on 2026-01-31 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_types_experience_and_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
