# Generated by Django 5.2.10 on 2026-02-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0005_jobapplication_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="interview_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
